BEGIN TRANSACTION;

CREATE TABLE WORKSPACE (ID INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT NOT NULL,  PATH TEXT NOT NULL );

CREATE TABLE "RESOURCE" (
	`ID`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`NAME`	TEXT NOT NULL,
	`RELATIVE_PATH`	TEXT NOT NULL,
	`ABSOLUTE_PATH`	TEXT NOT NULL,
	`CHANGESET_ID`	INTEGER NOT NULL,
	`OPERATION_TYPE`	INTEGER DEFAULT 1,
	`REVISION`	TEXT,
	FOREIGN KEY(`CHANGESET_ID`) REFERENCES `CHANGESET`(`ID`)
);

CREATE TABLE CHANGESET (ID INTEGER PRIMARY KEY AUTOINCREMENT, 
NAME TEXT NOT NULL,  
COMMIT_DATE_TIME INTEGER NULL,  
WORKSPACE_ID INTEGER NOT NULL, 
COMMITED INTEGER DEFAULT 0, 
FOREIGN KEY(WORKSPACE_ID) REFERENCES WORKSPACE(ID));

CREATE INDEX R_INDEX ON RESOURCE (NAME, RELATIVE_PATH ASC);
CREATE INDEX CHS_INDEX ON CHANGESET (NAME ASC,COMMIT_DATE_TIME ASC);
COMMIT;
